baseurl = "/"
languageCode = "en-us"
title = "A data and technology blog"
theme = "hugo-lithium"
enableEmoji = true
googleAnalytics = "UA-21866883-2"
disqusShortname = "msaliciabrown-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

# colors: https://github.com/karthik/wesanderson#the-darjeeling-limited-2007-
[[menu.main]]
    name = " "
    identifier = "home"
    pre = "<span title='blog posts' style='color: DodgerBlue;'><i class='fas fa-feather fa-lg'></i></span>"
    url = "/"
    weight = 1
[[menu.main]]
    name = " "
    identifier = "data"
    pre = "<span title='data vizes' style='color: #FF0000;'><i class='fas fa-chart-line fa-lg'></i></span>"
    url = "/data"
    weight = 2
[[menu.main]]
    name = " "
    identifier = "rstudio"
    pre = "<span title='a field guide to open data' style='color: #00A08A;'><i class='fas fa-book fa-lg'></i></span>"
    url = "https://open-data-people.github.io/open-data-field-guide/"
    weight = 3
[[menu.main]]
    name = " "
    identifier = "github"
    pre = "<span title='code repo' style='color: #F2AD00;'><i class='fab fa-github fa-lg'></i></span>"
    url = "https://github.com/aliciatb/"
    weight = 4
[[menu.main]]
    name = " "
    identifier = "linkedin"
    pre = "<span title='linked in profile' style='color: #F98400;'><i class='fab fa-linkedin fa-lg'></i></span>"
    url = "https://www.linkedin.com/in/aliciabrown"
    weight = 5
[[menu.main]]
    name = " "
    identifier = ""
    pre = "<span title='about me' style='color: #046C9A;'><i class='fas fa-info-circle fa-lg'></i></span>"
    url = "/about/"
    weight = 6

[params]
    description = "A website built through Hugo and blogdown."
    customCSS = ["css/tables.css"]
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.

    

