---
date: "2022-08-07"
title: Democratizing data & decision making
output:
  blogdown::html_page:
    toc: false
bibliography: references.bib
---

## Research Question

What are local government agencies and departments doing to enable community members to use open data for making decisions?

## Research Problem(s)

-   While making open data available is a great first step for agencies, it doesn't mean that they have made it accessible and usable for everyone.

-   I think that there is a gap in how local governments provide data to the public so they can analyze it and make informed decisions.

-   I believe that there are ways that agencies can successfully enable the public to use open data through training and community partnerships.

-   I think that information technology teams can contribute significantly to community enablement and that their participation is critical to support less resourced agencies and organizations.

## Research Plan/Methods

1.  **Literature review** to see what research has been done on enabling the public to use open data for decision making. Learn where I can contribute new knowledge on how to increase the use of open data by the public.
2.  **Identify** and **Interview** people involved with initiatives across the US where local government agencies are actively engaged with community members to support their use of open data. From these interviews I want to learn what drives successful community enablement and open data utilization.
3.  **Synthesize** what I learn to develop a plan for **participatory action research** in partnership with a King County agency or organization in the Puget Sound region for a data related initiative to validate new ways of enabling people to use government data. This will also give me the opportunity to contribute to my community by developing technical and analytic capacity.

## Research Outcomes

The products of my research will result in a dissertation by portfolio consisting of research articles and an educational component about community engagement and enablement on open data.

## Literature

### Public Administration & Policy

1.  [@frederickson2005]
2.  [@wooldridge2009]
3.  [@powell2009]
4.  [@guy2012]
5.  [@pastor2018]

### Feminist Theory

1.  [@hooks2000a]
2.  [@cottom2018]

### Critical Data & Technology

1.  [@reardon2012]
2.  [@lewis2018]
3.  [@noble2018]
4.  [@criado-perez2019]
5.  [@dignazio2020]
6.  [@madianou2019]
