---
title: "Alicia Brown's resume"
author: Alicia Brown
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

Main
================================================================================

Alicia Brown {#title}
--------------------------------------------------------------------------------

Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Technical Solution Architect

Tyler Technologies - Data and Insights Division

Seattle, WA

2018 - present

- Partner with public sector agencies and governments to share their data within their organization and community for informed decision-making and transparency
- Empower the discovery of insights in data by teams via Data Science and Business Intelligence Tools and Programming Languages (Power BI, Tableau, R, Python, SQL, Excel, Power Query)
- Provides guidance on establishing strong Data Governance programs to ensure the integrity, availability and accessibility of data

### Senior Data Analyst

Socrata

Seattle, WA

2018 - 2015

- Enable the automation of data retrieval from internal sources and external APIs
- Develop solutions leveraging products, custom ETL, development and consulting services

### Technical Project Manager

HD Vest Financial Services

Seattle, WA

2013 - 2010

- Led migration of applications, data and files from Wells Fargo servers to new H.D. Vest environment
- Worked closely with cross functional teams across the organization to ensure successful execution of change requests and migration events
-	Led sustainability team to improve robustness of portal web applications

### Team Lead / Senior Web Developer

Wells Fargo Advisors

Seattle, WA

2010 - 2007

-	Led portal team integration project with Wachovia platform (data migration, SSO, login, and application integration)

### Web Developer

Wells Fargo

Dallas, TX

2000 - 2007

-	Full stack developer of web applications using C#, VB.net, VBScript, SQL for Advisor and Client sites

Certifications {data-icon=certificate}
--------------------------------------------------------------------------------

### Certified Scrum Master (CSM®)

Scrum Alliance

Seattle, WA

### Techniques for Decision Making

University of Washington

Seattle, WA

### Mastering Software Development in R Specialization

Johns Hopkins University

Coursera

Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### Texas Christian University

Masters of Business Administration (MBA)

Fort Worth, TX



### Texas A&M University

Bachelors of Arts Anthropology

College Stations, TX

