---
title: "Alicia Brown's Resume"
author: Alicia Brown
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    self_contained: true
---

Aside
================================================================================

Connect{#connect}
--------------------------------------------------------------------------------

- [linkedin.com/in/aliciabrown](https://www.linkedin.com/in/aliciabrown/)
- [github.com/aliciatb](https://github.com/aliciatb)
- +1 206-265-9090

Toolset {#toolset}
--------------------------------------------------------------------------------

- R, Python, SQL, Notebooks, Microsoft Power BI, Tableau, Power Platform, ArcGIS Pro, ArcGIS Online, FME, Informatica

- Data Engineering, Spatial Analysis, Visualization, Storytelling, Governance, Contextualization

- Agile Development, Scrum, Kanban, Design Thinking

Main
================================================================================

Alicia Brown {#title}
--------------------------------------------------------------------------------

### 

- Champion of Business Intelligence dashboards and spatial data tools 
- 8+ years consulting experience for government data programs
- 10+ years leading technical and data architecture projects
- 10+ years web and data application development experience

Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Solutions Architect

King County, WA - Data & Analytics

Seattle, WA

present - 2020

- Criminal Justice Azure data hubs
- Equity & Social Justice ArcGIS hub and Azure data hub
- PPE allocation algorithm and reporting development 

### Technical Solution Architect

Socrata / Tyler Tech - Data and Insights Division

Seattle, WA

2020 - 2018

- Architect solutions for clients by capturing business requirements from departments and design partners
- Develop data applications to bridge gaps between sales, customer success and product development teams
- Provide guidance to team and clients on developing reusable and scalable solutions

### Senior Data Analyst

Socrata - Global Services

Seattle, WA

2018 - 2015

- Evangelize best practices on Data Governance, Metadata, Standards, Quality, Privacy and Security
- Empowered the discovery of insights in data by teams via Data Science and Business Intelligence Tools and Programming Languages (Power BI, Tableau, R, Python, SQL, Excel, Power Query)
- Developed custom ETL (Extract-Transform-Load) for multiple client tools and source systems
- Enabled the automation of data retrieval from external APIs for tracking performance across common indicators and bench marking against peers

### Technical Project Manager

H.D. Vest Financial Services / Wells Fargo Advisors

Seattle, WA

2013 - 2010

- Led migration of applications, data and files from Wells Fargo servers to new H.D. Vest environment
- Worked closely with cross functional teams across the organization to ensure successful execution of change requests and migration events
-	Led sustainability team to improve robustness of portal web applications

### Senior Web Developer

H.D. Vest Financial Services / Wells Fargo Advisors

Dallas, TX

2010 - 2000

-	Led portal team integration project with Wachovia platform (data migration, SSO, login, and application integration)
-	Full stack developer of web applications using C#, VB.net, VBScript, SQL for Advisor and Client sites

Projects {data-icon=globe}
--------------------------------------------------------------------------------

### Determinants of Equity Report

[kingcounty.gov](https://kingcounty.gov/en/legacy/elected/executive/equity-social-justice/determinantsofequity)

King County, WA

2023

Interactive report built on ArcGIS Online products to provide information about equity across King County based on the 15 Determinants of Equity.

### Data-Driven PPE Allocation Algorithm

[doi.org/10.1089/hs.2022.0115](https://doi.org/10.1089/hs.2022.0115)

King County, WA

2022 - 2020

Supported and contributed to the code of the allocation algorithm and reports used by the Health Medical Area Command (HMAC) and Public Health Seattle-King County (PHSKC) to distribute PPE across the county.

###  California State Auditor's Local Government High-Risk Dashboard

[]()

Sacramento, CA

2019


Fiscal Health Indicator Map and Dashboard showing the fiscal health of California cities.

### Pierce County Performance Dashboards

[open.piercecountywa.gov](https://open.piercecountywa.gov)

Pierce County, WA

2018

Performance Management Data and Dashboards for County Services and Community Indicators.

### Oakland Equity Indicators

[data.oaklandca.gov/stories/s/brb2-j4ad](https://data.oaklandca.gov/stories/s/brb2-j4ad)

Oakland, CA

2018

Interactive report of Equity Scores for 72 indicators across six themes highlighting opportunities for city investments

### Neighborhood Data for Social Change Platform

[ladata.myneighborhooddata.org](https://ladata.myneighborhooddata.org)

Los Angeles, CA

2017

Community Data, Dashboards and Storytelling platform for researchers and local non-profits in Southern California

### Michigan Financial & School Dashboards

[micommunityfinancials.michigan.gov](http://micommunityfinancials.michigan.gov)

Lansing, MI

2016

Dashboards built for the Michigan Department of Treasury / Schools to monitor financial and enrollment data across localities and educational entities


Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### Royal Roads University

Doctoral Candidate - Social Sciences

Victoria, BC

### Texas Christian University

Masters of Business Administration

Fort Worth, TX


### Texas A&M University

Bachelors of Arts - Anthropology

College Station, TX

Certifications {data-icon=certificate}
--------------------------------------------------------------------------------

### Certified Scrum Master (CSM®)

Scrum Alliance

Seattle, WA

### BI - Techniques for Decision Making

University of Washington

Seattle, WA
